# headline for the playbook
- name: Create lab user accounts
  hosts: local
  connection: local
  gather_facts: True

# declare the variables to use
vars:
  username: "igxuser"
  password: "IGXuser"

# Declare the tasks to run in the playbook
  tasks:
    - name: add several users
      user:
        name: "{{ username }}{{ item }}"
        password: "{{ password }}{{ item }}"
        state: present
      with_sequence:
         - count=8
