# headline for the playbook
- name: date check
  hosts: local
  connection: local
  gather_facts: False

# Declare the tasks to run in the playbook

  tasks:
    - name: get credentials
      include_vars: 'credentials_list.yml'
      no_log: 'no'

    - name: Print multiple device credentials
      debug:
        msg: "The IP address is {{ item.ip_address }}"
      with_items: "{{ credentials }}"
