# headline for the playbook
- name: date check
  hosts: local
  connection: local
  gather_facts: False

  vars_prompt:
   - name: my_name
     prompt: "Please provide your name"
     private: no
     failed_when: my_name is undefined
# Declare the tasks to run in the playbook
  tasks:
  - name: get credentials
    include_vars: 'credentials.yml'
    no_log: 'no'

  - name: Print input results
    debug:
      msg: "The input is {{ my_name }}"
      
  - name: Print credentials results
    debug:
      msg: "The IP address is {{ fw_creds.ip_address }}"
