# headline for the playbook
- name: admin check
  hosts: panorama
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    ip_to_register: "10.10.10.10"
    tag_names: ["wp-test-app"]
    dag_name: "wp-test-dag"
    dag_match_filter: "'wp-test-app'"
    devicegroup: "wp-test-dg"

# Declare the tasks to run in the playbook
  tasks:
  - name: get credentials
    include_vars: 'pano_provider.yml'
    no_log: 'no'

  - name: Check Panorama is Ready for Config
    panos_check:
      provider: '{{ provider }}'
      initial_delay: 5
      interval: 5
      timeout: 60
    register: result

  - name: Print check results
    debug:
      var: result

  - name: add test-app inbound rule to Panorama device group
    panos_security_rule:
      provider: '{{ provider }}'
      device_group: "{{ devicegroup }}"
      rule_name: 'wp-rule-test'
      description: 'WP rule test'
      tag_name: ['test']
      source_zone: ['any']
      source_ip: ['wp-test-dag']
      destination_zone: ['any']
      destination_ip: ['1.1.1.1']
      application: ['ssl']
      action: 'allow'
    register: rule

  - name: Print rule results
    debug:
      var: rule
