# Test file for URI module and conditionals
- name: admin check
  hosts: local
  connection: local
  gather_facts: False

  vars_prompt:
   - name: giveName
     prompt: "Please provide your name"
     private: no
     failed_when: giveName is undefined

  tasks:
  - name: Post a message to slack
    uri:
      url: https://www.willembrey.com
      method: GET
      return_content: yes
    register: result

  - name: Show output with debug
    debug:
      var: result

  - name: Show content with debug
    debug:
      var: result.content

- hosts: all
  remote_user: root
  gather_facts: yes
  vars_prompt:
   - name: giveName
     prompt: "Please provide your name"
     private: no
     failed_when: giveName is undefined
 tasks:
  - name: Python Execution
    testing: yourName={{ giveName }}
    register: result
  - debug: var=result
