# headline for the playbook
- name: admin check
  hosts: panorama
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

# Declare the tasks to run in the playbook
  tasks:
  - name: get credentials
    include_vars: 'fw_provider.yml'
    no_log: 'no'

  - name: Check Panorama is Ready for Config
    panos_check:
      provider: '{{ provider }}'
      initial_delay: 5
      interval: 5
      timeout: 60
    register: result

  - name: Print check results
    debug:
      var: result

  - name: Get Facts
    panos_facts:
      provider: '{{ provider }}'
    register: facts

  - name: Print facts
    debug:
      var: facts
