# Test file for URI module and conditionals

- name: admin check
  hosts: local
  connection: local
  gather_facts: False

  vars_prompt:
- name: giveName
     prompt: "Please provide your name"
     private: no
     failed_when: giveName is undefined

 tasks:
  - name: Print check results
    debug:
      msg: "Your input was {{ givename }} "
