# headline for the playbook
- name: Remove lab user accounts
  hosts: local
  connection: local
  gather_facts: True

# declare the variables to use
  vars:
    username: "igxuser"


# Declare the tasks to run in the playbook
  tasks:
    - name: Remove users "igxuser1" to "igxuser8"
      user:
        name: "{{ username }}{{ item }}"
        state: absent
        remove: yes
        force: yes
      become: yes
      with_sequence:
         - count=10
