# headline for the playbook
- name: Remove lab user accounts
  hosts: local
  sudo: yes
  sudo_user: wembrey
  connection: local
  gather_facts: True

# declare the variables to use
  vars:
    username: "igxuser"


# Declare the tasks to run in the playbook
  tasks:
    - name: Remove users "igxuser1" to "igxuser8"
      shell: "userdel {{ username }}{{ item }}"
      become: yes
      with_sequence:
         - count=8

    - name: remove home directories
      file:
        path: "/home/{{username}}{{item}}"
        state: absent
      with_sequence:
        - count=8
